[package]
name = "bubblegumsdk_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "bubblegumsdk_native"
crate-type = ["cdylib"]

[dependencies]
mpl-bubblegum = "1.4.0"
rustler = "0.36.1"
solana-program = "2.2.1"
